config/routes.rb
Rails.application.routes.draw do

  root to: 'products#catalogue'

  get 'catalogue', to: 'products#catalogue'
  # get 'products/catalogue'
  get 'products/cart', to: 'products#cart', as: :cart
  get 'products/:id', to: 'products#view', as: :product
  get 'products/:id/added', to: 'products#add', as: :add
  get 'products/:id/removed', to: 'products#remove', as: :remove


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  @@cart = []

  def catalogue
    if params[:name_search].nil? || params[:name_search].empty?
      @catalogue = Product.all
    else
      # @catalogue = Product.select do |product|
      #   product.energy_kcal_100g <= params[:calorie_count].to_f
      # end
      @catalogue = Product.where("name LIKE ?", "%#{params[:name_search]}%")
    end
  end

  def view
    @product = Product.find(params[:id].to_i)
  end

  def add
    @product = Product.find(params[:id].to_i)
    @@cart << @product
    @cart = @@cart
  end

  def cart
    @cart = @@cart
  end

  def remove
    @product = Product.find(params[:id].to_i)
    @@cart.delete(@product)
    @cart = @@cart
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommerceStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <!-- <header><%= link_to "Home", root_path %> <%= link_to "Cart", cart_path %></header> -->



  <body>
    <div class="myheader">
      <div class="myheader-link">
      <%= link_to "Home", root_path %>
      </div>
      <div class="myheader-link">
       <%= link_to "Cart", cart_path %>
      </div>
    </div>

    <div class="content">
       <%= yield %>
    </div>

   <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/products/_cartlist.html.erb
<div class="cart-list-container">
  <div class="cart-list">
    <h2>Your cart items</h2>
    <ul>
      <% @cart.each do |product| %>
        <li>
          <%= product.name%> <%= link_to "(Remove)", remove_path(id: product.id) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/products/add.html.erb
<h2>Successfully added <%= @product.name %></h2>

<%= render "cartlist", locals: {cart: @cart} %>

app/views/products/cart.html.erb
<h1>Your cart</h1>

<%= render "cartlist", locals: {cart: @cart} %>

app/views/products/catalogue.html.erb
<h1>Our Catalogue</h1>

  <div class="search-form">
    <form action="/catalogue" method = "get">
      <input type="text" name="name_search" placeholder="Search">
      <input type="submit" value="Search">
    </form>
  </div>

  <div class="card-container">
    <% @catalogue.each do |product| %>
      <div class="card-catalogue">
        <div class="card-catalogue-title">
          <!-- <%= link_to product.name, product_path(id: product.id)%> -->
          <%= link_to product_path(id: product.id) do %>
            <div class="card-catalogue-title-link">
                <%= product.name %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

app/views/products/remove.html.erb
<h2>Successfully removed <%= @product.name %></h2>

<%= render "cartlist", locals: {cart: @cart} %>

app/views/products/view.html.erb
<div class="card-product-container">
  <div class="card-product">
    <h1><%= @product.name %></h1>
    <ul>
      <li><strong>Category:</strong> <%=@product.categories%></li>
      <li><strong>KCAL per 100g:</strong> <%= @product.energy_kcal_100g %></li>
      <li><strong>URL:</strong> <%= @product.url %></li>
    </ul>
    <div class="card-product-add">
      <p><%= link_to "Add to Cart", add_path(id: @product.id)%></p>
    </div>
  </div>
</div>